import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/component/NavBar";
import { AuthProvider } from "./Providers";

export const metadata: Metadata = {
  title: "HeyJobs portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        

       <AuthProvider>
       <NavBar />
          {children}
       </AuthProvider>
        
      </body>
    </html>
  );
}
